### ISSUE TITLE
Missing observables in logWhatIChange output

### ISSUE THREAD

**Issue by m-mujica** [canjs/can-debug#24]
```js
var debug = require("can-debug");
var stache = require("can-stache");
var DefineMap = require("can-define/map/map");
require("can-stache-bindings");

var Person = DefineMap.extend("Person", {
  first: "string",
  last: "string",
  fullName: {
    get() {
      return `${this.first} ${this.last}`;
    }
  }
});

var view = stache(`
	<h1 id="full">{{fullName}}</h1>
	<input id="first" value:bind="first">
	<input id="last" value:bind="last">
`);

var scope = new Person({ first: "Jane", last: "Doe" });
document.body.appendChild(view(scope));

debug.logWhatIChange(document.querySelector("#first"), "value");
```

The output does not includes `fullName`.

**Comment by m-mujica** [comment]
These PRs need to be reviewed and merged

- [ ] [Missing ScopeKeyData getWhatIChange](https://github.com/canjs/can-view-scope/pull/134)
- [ ] [Missing getWhatIChange in map/legacy events](https://github.com/canjs/can-event-queue)
- [ ] [Missing callback changes symbol](https://github.com/canjs/can-stache-bindings/pull/379)

Fixed output looks like this:

![screen shot 2017-12-08 at 4 54 19 pm](https://user-images.githubusercontent.com/724877/33790832-15d12f4c-dc41-11e7-857b-638e7192ed9f.png)

**Comment by justinbmeyer** [comment]
What do you think about changing `derived dependencies` to `derive dependencies`?  `derived` sounds like those dependencies are _derived from_ the parent dependency. _derive_ might be a bit better.

**Comment by justinbmeyer** [comment]
Or maybe `DERIVED FROM`,  `MUTATED BY`, and `TWO WAY`

**Comment by m-mujica** [comment]
Ok, I'm going to update can-debug to use those labels instead. 

Did you take a look at the other PRs? Mind if I merge those?
