### ISSUE TITLE
Make can-debug registration work in 5.0

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-debug#46]
Since `can-debug` is side-effectual:

https://github.com/canjs/can-debug/blob/f40c07c24fdfdaa746e8047b104aa9393633099d/can-debug.js#L23-L27

we'll need to figure out how to make this work in 5.0.

We could require people to import `debug` and set the global themselves:
```
import {Component, debug} from "can";
window.can = debug;
```

or maybe calling `debug` does this:

```
import {Component, debug} from "can";
debug();
```

or maybe we do something like jquery-noconflict:
```
import {Component, debug} from "can";
window.CAN = debug(true);
```

I don't know exactly how this should work, just some ideas from discussing with @justinbmeyer.

cc @matthewp.

**Comment by phillipskevin** [comment]
related to  https://github.com/canjs/canjs/issues/4202.

**Comment by matthewp** [comment]
If you're worried about tree-shaking, this would only be removed during the build, but you probably want that anyways.

**Comment by matthewp** [comment]
I don't think this is needed for 5.0. As said, you can attach to the window if you want it in production, otherwise it will only be tree-shaken in prod.

**Comment by phillipskevin** [comment]
I think we should still make it possible to use `can-debug` with the module build. Currently, if you're using the `.mjs` file, it's not possible to import `can-debug` like this:

```
import {Component, debug} from "//unpkg.com/can/core.mjs";
```

This means that you can't use devtools or other `can-debug` functionality if you're importing the `.mjs` file like this.

**Comment by matthewp** [comment]
Is it supposed to be part of core? It's currently in the ecosystem build: https://github.com/canjs/canjs/blob/master/ecosystem.js#L2, so `import {Component, debug} from "//unpkg.com/can/ecosystem.mjs";` should work.

**Comment by justinbmeyer** [comment]
Probably should be in ecosystem because of how big the graph is. Though I wonder if we can have a “minor” version in ecosystem.

**Comment by phillipskevin** [comment]
I'm going to make the main module export a function, so if you want to use it with tree-shaking (w/ webpack, or steal 2.0 in a production build) you would do:

```js
// your app.js
import { debug } from "can";

debug();
```

We will also add it to the main can core.js file so in development mode `debug` will be enabled:
```js
// canjs/canjs/core.js
import { debug } from "can";

//!steal-remove-start
if(process.env.NODE_ENV !== 'production') {
  debug();
}
//!steal-remove-end
```
